// src/lib/spots.ts
import { Spot } from '@/types';

export const SPOTS: Spot[] = [
  {
    id: 'apelviken',
    name: 'Apelviken',
    region: 'Halland',
    lat: 57.1167,
    lng: 12.2667,
    description: '',
    difficulty: 'beginner',
    bestWind: 'NO/O (offshore)',
    bestSwell: 'SV/V',
    bestTide: 'Alla tidvatten',
    imageKey: 'apelviken',
  },
  {
    id: 'skrea',
    name: 'Skrea Strand',
    region: 'Halland',
    lat: 56.9000,
    lng: 12.5000,
    description: '',
    difficulty: 'beginner',
    bestWind: 'O (offshore)',
    bestSwell: 'SV/V',
    bestTide: 'Medel',
    imageKey: 'skrea',
  },
  {
    id: 'ringenas',
    name: 'Ringenäs',
    region: 'Halland',
    lat: 56.8000,
    lng: 12.5500,
    description: '',
    difficulty: 'intermediate',
    bestWind: 'O (offshore)',
    bestSwell: 'V',
    bestTide: 'Alla tidvatten',
    imageKey: 'ringenas',
  },
  {
    id: 'tylosand',
    name: 'Tylösand',
    region: 'Halland',
    lat: 56.6667,
    lng: 12.5000,
    description: '',
    difficulty: 'beginner',
    bestWind: 'NNO (offshore)',
    bestSwell: 'SV/V',
    bestTide: 'Alla tidvatten',
    imageKey: 'tylosand',
  },
  {
    id: 'skaret',
    name: 'Skäret',
    region: 'Skåne',
    lat: 56.2333,
    lng: 12.5667,
    description: '',
    difficulty: 'intermediate',
    bestWind: 'O/SO (offshore)',
    bestSwell: 'V/NV',
    bestTide: 'Medel till hög',
    imageKey: 'skaret',
  },
  {
    id: 'molle',
    name: 'Mölle',
    region: 'Skåne',
    lat: 56.2833,
    lng: 12.4833,
    description: '',
    difficulty: 'advanced',
    bestWind: 'NV→N (optimal 337°)',
    bestSwell: 'NV',
    bestTide: 'Låg till medel',
    imageKey: 'molle',
  },
  {
    id: 'kaseberga',
    name: 'Kåseberga',
    region: 'Skåne',
    lat: 55.3833,
    lng: 14.0500,
    description: '',
    difficulty: 'intermediate',
    bestWind: 'V (offshore)',
    bestSwell: 'O/SO',
    bestTide: 'Alla tidvatten',
    imageKey: 'kaseberga',
  },
  {
    id: 'baskemolla',
    name: 'Baskemölla',
    region: 'Skåne',
    lat: 55.5833,
    lng: 14.2167,
    description: '',
    difficulty: 'beginner',
    bestWind: 'V/NV (offshore)',
    bestSwell: 'O/SO',
    bestTide: 'Medel',
    imageKey: 'baskemolla',
  },
];

export const getSpotById = (id: string): Spot | undefined =>
  SPOTS.find(s => s.id === id);
